<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laporan Disposisi</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 3px solid #F59E0B;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 5px 0;
            color: #F59E0B;
            font-size: 20px;
        }
        .header p {
            margin: 3px 0;
            color: #666;
        }
        .stats {
            display: table;
            width: 100%;
            margin-bottom: 20px;
            background-color: #F3F4F6;
            padding: 10px;
            border-radius: 5px;
        }
        .stat-item {
            display: table-cell;
            text-align: center;
            padding: 10px;
        }
        .stat-item strong {
            display: block;
            font-size: 24px;
            color: #F59E0B;
            margin-bottom: 5px;
        }
        .stat-item span {
            color: #666;
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #F59E0B;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 10px;
            font-weight: bold;
        }
        td {
            padding: 6px 8px;
            border-bottom: 1px solid #E5E7EB;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background-color: #F9FAFB;
        }
        .badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-pending { background-color: #FEF3C7; color: #92400E; }
        .badge-proses { background-color: #DBEAFE; color: #1E40AF; }
        .badge-selesai { background-color: #D1FAE5; color: #065F46; }
        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 LAPORAN DISPOSISI</h1>
        <p>Periode: {{ \Carbon\Carbon::parse($startDate)->format('d/m/Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d/m/Y') }}</p>
        <p>Dicetak pada: {{ date('d/m/Y H:i:s') }}</p>
    </div>

    <div class="stats">
        <div class="stat-item">
            <strong>{{ $stats['total'] }}</strong>
            <span>Total Disposisi</span>
        </div>
        <div class="stat-item">
            <strong>{{ $stats['pending'] }}</strong>
            <span>Pending</span>
        </div>
        <div class="stat-item">
            <strong>{{ $stats['proses'] }}</strong>
            <span>Proses</span>
        </div>
        <div class="stat-item">
            <strong>{{ $stats['selesai'] }}</strong>
            <span>Selesai</span>
        </div>
    </div>

    <h3 style="margin-top: 20px; margin-bottom: 10px; color: #F59E0B; font-size: 14px; font-weight: bold;">
        TABEL DATA DISPOSISI
    </h3>

    <table>
        <thead>
            <tr>
                <th width="4%">NO</th>
                <th width="12%">NO. SURAT</th>
                <th width="10%">TGL DISPOSISI</th>
                <th width="12%">DARI</th>
                <th width="13%">KEPADA</th>
                <th width="25%">INSTRUKSI</th>
                <th width="15%">CATATAN</th>
                <th width="10%">STATUS</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $item)
            <tr>
                <td style="text-align: center;">{{ $index + 1 }}</td>
                <td>{{ $item->suratMasuk->nomor_surat ?? '-' }}</td>
                <td>{{ $item->tanggal_disposisi ? $item->tanggal_disposisi->format('d/m/Y') : '-' }}</td>
                <td>{{ $item->dariUser->name ?? '-' }}</td>
                <td>{{ $item->kepadaUser->name ?? '-' }}</td>
                <td>{{ $item->instruksi }}</td>
                <td>{{ $item->catatan ?? '-' }}</td>
                <td>
                    <span class="badge badge-{{ $item->status }}">
                        {{ strtoupper($item->status) }}
                    </span>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="8" style="text-align: center; padding: 20px; color: #999;">
                    Tidak ada data untuk periode yang dipilih
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Sistem E-Arsip | Generated by {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
