<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laporan Surat Keluar</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 3px solid #10B981;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 5px 0;
            color: #10B981;
            font-size: 20px;
        }
        .header p {
            margin: 3px 0;
            color: #666;
        }
        .stats {
            display: table;
            width: 100%;
            margin-bottom: 20px;
            background-color: #F3F4F6;
            padding: 10px;
            border-radius: 5px;
        }
        .stat-item {
            display: table-cell;
            text-align: center;
            padding: 10px;
        }
        .stat-item strong {
            display: block;
            font-size: 24px;
            color: #10B981;
            margin-bottom: 5px;
        }
        .stat-item span {
            color: #666;
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #10B981;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 10px;
            font-weight: bold;
        }
        td {
            padding: 6px 8px;
            border-bottom: 1px solid #E5E7EB;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background-color: #F9FAFB;
        }
        .badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-draft { background-color: #FEF3C7; color: #92400E; }
        .badge-approved { background-color: #DBEAFE; color: #1E40AF; }
        .badge-sent { background-color: #D1FAE5; color: #065F46; }
        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📤 LAPORAN SURAT KELUAR</h1>
        <p>Periode: {{ \Carbon\Carbon::parse($startDate)->format('d/m/Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d/m/Y') }}</p>
        <p>Dicetak pada: {{ date('d/m/Y H:i:s') }}</p>
    </div>

    <div class="stats">
        <div class="stat-item">
            <strong>{{ $stats['total'] }}</strong>
            <span>Total Surat</span>
        </div>
        <div class="stat-item">
            <strong>{{ $stats['draft'] }}</strong>
            <span>Draft</span>
        </div>
        <div class="stat-item">
            <strong>{{ $stats['approved'] }}</strong>
            <span>Approved</span>
        </div>
        <div class="stat-item">
            <strong>{{ $stats['sent'] }}</strong>
            <span>Sent</span>
        </div>
    </div>

    <h3 style="margin-top: 20px; margin-bottom: 10px; color: #10B981; font-size: 14px; font-weight: bold;">
        TABEL DATA SURAT KELUAR
    </h3>

    <table>
        <thead>
            <tr>
                <th width="4%">NO</th>
                <th width="15%">NO. SURAT</th>
                <th width="10%">TGL SURAT</th>
                <th width="20%">TUJUAN</th>
                <th width="30%">PERIHAL</th>
                <th width="11%">LAMPIRAN</th>
                <th width="10%">STATUS</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $item)
            <tr>
                <td style="text-align: center;">{{ $index + 1 }}</td>
                <td>{{ $item->nomor_surat }}</td>
                <td>{{ $item->tanggal_surat ? $item->tanggal_surat->format('d/m/Y') : '-' }}</td>
                <td>{{ $item->tujuan }}</td>
                <td>{{ $item->perihal }}</td>
                <td style="text-align: center;">{{ $item->lampiran ?? '-' }}</td>
                <td>
                    <span class="badge badge-{{ $item->status }}">
                        {{ strtoupper($item->status) }}
                    </span>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center; padding: 20px; color: #999;">
                    Tidak ada data untuk periode yang dipilih
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Sistem E-Arsip | Generated by {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
